apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  labels:
    elasticsearch: kibana-logging

spec:
  selector:
    elasticsearch: kibana-logging
  ports:
  - port: 5601            
    targetPort: 5601 
    name: "ui"
